### ISSUE TITLE
Can't update since 5.0.3

### ISSUE THREAD

**Issue by Mister-XY** [LS80/script.openelec.devupdate#14]
Hello, if i'm using the devupdate and openelec 5.0.3, it can't find any updates. 
I'm allways get a message "No Build were found for rpi2.arm.
http://releases.openelec.tv Please check the URL in the addon settings."
The Problem is with Raspberry Pi B and Raspberry Pi 2 the same.

**Comment by LS80** [comment]
Yes unfortunately there is no longer a listing of downloads at http://releases.openelec.tv for the addon to read. I will change the url for the listing to http://openelec.mirrors.uk2.net/. It won't be the closest mirror for those not in the UK but it's only 70k so the difference should be negligible. The downloads themselves will still use the nearest mirror.
