### ISSUE TITLE
Milhouse custom source not found

### ISSUE THREAD

**Issue by MilhouseVH** [LS80/script.openelec.devupdate#20]
I'm currently uploading RPi/RPi2/Generic test builds to: http://milhouse.openelec.tv/builds/wipupnp

I've added a custom source to my RPi2 (all other settings are default):

![image](http://i225.photobucket.com/albums/dd119/MilhouseVH/screenshot004_zpsxgfshqro.png)

but when checking for new builds, the following error occurs:

![image](http://i225.photobucket.com/albums/dd119/MilhouseVH/screenshot005_zpsi032xanu.png)

I also tried without specifying the RPi2 folder in the url, but the problem is the same - no builds found.

**Comment by LS80** [comment]
Thanks for reporting this. I've added a "Milhouse" option for Build type which should fix it.
