### ISSUE TITLE
/etc/version is dropped from latest master builds

### ISSUE THREAD

**Issue by MilhouseVH** [LS80/script.openelec.devupdate#24]
Hi Leopold

Following the merge of [#4285](https://github.com/OpenELEC/OpenELEC.tv/pull/4285), the `/etc/version` file is no longer created (see [here](https://github.com/OpenELEC/OpenELEC.tv/pull/4285/files#diff-9c7eee3ed0931e5ee6bcba810283ece0L92)).

When `/etc/version` doesn't exist, the DevUpdate addon triggers the [IOException](https://github.com/LS80/script.openelec.devupdate/blob/master/resources/lib/builds.py#L397) which results in your test value being used.

You'll probably need to update the addon to extract the `VERSION` value from `/etc/os-release` and use that in place of the value you were reading from `/etc/version`.

I'll add a patch to tonight's test build (and include it for the next few days) so that `/etc/version` continues to be created as this will prevent the current DevUpdate addon from continually thinking there is a new version available. Once you've been able to push an update I'll drop the patch.

**Comment by LS80** [comment]
It looks like `/etc/arch` has also been removed which will mean that RPi2 users will inadvertently install an RPi build!

As you say I'll have to parse all of this from `/etc/os-release` instead.

**Comment by MilhouseVH** [comment]
Argh... should I pull the build? I can create /etc/arch temporarily if required.

**Comment by LS80** [comment]
It's possible to override the build type in the add-on settings, so maybe just add a note to suggest to set it to RPi2?

**Comment by MilhouseVH** [comment]
I have no idea how many are reading the forum, compared with those that just update automatically via the addon. I'll pull the build and push an #0802b with `/etc/arch`.

**Comment by LS80** [comment]
OK sounds good.

**Comment by LS80** [comment]
Sorry but the `/etc/openelec-release` removal also causes a problem for the add-on. The tar files will end up in the temp directory instead of .update

**Comment by MilhouseVH** [comment]
OK, sounds like the safest thing to do would be to revert #4285 until you have an update available.

I'll push #0822b with #4285 reverted.

**Comment by LS80** [comment]
Yes sounds like the safest thing. I'll get an update out ASAP.

**Comment by MilhouseVH** [comment]
Thanks for the quick fix. I'll continue to revert #4285 for up to a week (as long as there are no other conflicting commits) to allow more users to auto-update the add-on before finally dropping the revert.
