### ISSUE TITLE
OpenElec dev update error

### ISSUE THREAD

**Issue by mka29** [LS80/script.openelec.devupdate#30]
Hello,
My openElec updater gives me an error and I can't find any new info online on how to fix it
Can you please help?

Your debug kodi.log: http://xbmclogs.com/p3h3lfxkz
Your debug kodi.log: http://xbmclogs.com/pv9s8txcv

Thank you,
mka29

**Comment by AxelF0ley** [comment]
Same problem, here's my log: http://xbmclogs.com/prrrh3bss

**Comment by harakiwi** [comment]
i'm using (finally!) my RasPi0, i'm trying to update to the dev builds (already running fine on my Pi2!) 
but the addon won't run / start with an error

http://xbmclogs.com/p2yl0uc2m

**Comment by LS80** [comment]
Logs no longer viewable, so closing the issue.
